In [64]:
import numpy as np
import random

#training input and ouput 
input = np.array([[0,0],[0,1],[1,0],[1,1]])
output = np.array([[0,1,1,0]]).T    #XOR operation

In [65]:
input_layer = 2
hidden_layer = 2
output_layer = 1

In [66]:
weights1 = 2 * np.random.random((input_layer,hidden_layer)) - 1
bias1 = 2 * np.random.random((1,hidden_layer)) - 1

weights2 = 2 * np.random.random((hidden_layer,output_layer)) - 1
bias2 = 2 * np.random.random((1,output_layer)) - 1

In [67]:
#activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def der(x):
    return x * (1-x)

In [68]:
predicted = []

for epochs in range(10000):
    #forward propagation
    weighted_sum1 = np.dot(input,weights1) + bias1
    curr_output1 = sigmoid(weighted_sum1)

    weighted_sum2 = np.dot(curr_output1,weights2) + bias2
    curr_output2 = sigmoid(weighted_sum2)

    error2 = output - curr_output2
    slope2 = der(curr_output2)
    delta2 = error2 * slope2

    error1 = np.dot(delta2,weights2.T)
    slope1 = der(curr_output1)
    delta1 = error1 * slope1

    weights2 += np.dot(curr_output1.T,delta2)
    weights1 += np.dot(input.T,delta1)

    bias2 += np.array([np.sum(delta2,axis=0)])
    bias1 += np.array([np.sum(delta1,axis=0)])

    predicted = curr_output2

print(weights1)
print(weights2)

[[-5.19390155 -6.33869353]
 [-5.19446743 -6.3408699 ]]
[[ 10.47300949]
 [-10.75457241]]


In [69]:
#predict
print(predicted)

[[0.01068734]
 [0.98887732]
 [0.98887578]
 [0.01365075]]


In [70]:
#accuracy
temp = (predicted - output) ** 2
acc = 0
for i in range(4):
    acc += temp[i][0]

print((1 - acc/4) * 100)

99.98629938890306
