In [10]:
import numpy as np
import pandas as pd

In [11]:
def PCA(X , num_components):
     
    X_meaned = X - np.mean(X , axis = 0)
     
    cov_mat = np.cov(X_meaned , rowvar = False)
     
    eigen_values , eigen_vectors = np.linalg.eigh(cov_mat)
     
    sorted_index = np.argsort(eigen_values)[::-1]
    sorted_eigenvalue = eigen_values[sorted_index]
    sorted_eigenvectors = eigen_vectors[:,sorted_index]
    
    eigenvector_subset = sorted_eigenvectors[:,0:num_components]
    
    print(eigenvector_subset)

    X_reduced = np.dot(eigenvector_subset.transpose() , X_meaned.transpose() ).transpose()
     
    return X_reduced

In [15]:
input = np.array([[1,2],[2,3],[3,2],[4,5],[5,4],[6,8],[9,7],[8,9]])
input

array([[1, 2],
       [2, 3],
       [3, 2],
       [4, 5],
       [5, 4],
       [6, 8],
       [9, 7],
       [8, 9]])

In [16]:
dimension = 1
reduced_data = PCA(input,dimension)

[[-0.72014174]
 [-0.69382697]]


In [17]:
reduced_data

array([[ 4.78201246],
       [ 3.36804374],
       [ 3.34172897],
       [ 0.54010631],
       [ 0.51379154],
       [-2.9816581 ],
       [-4.44825636],
       [-5.11576856]])