In [390]:
import numpy as np
import random
import pandas as pd

In [391]:
data = pd.read_csv('dataset.csv')
attributes = data.columns
data

x  y  output
0  0  0       0
1  0  1       1
2  1  0       0
3  1  1       1

In [392]:
temp_input = [[0 for i in range(len(attributes)-1)] for j in range(len(data))]

temp1 = data[attributes[-1]].values
temp2 = []
set = []

for e in temp1:
    if set.count(e) == 0:
        set.append(e)
        temp2.append(set.index(e))
    else:
        temp2.append(set.index(e))

output = np.array([temp2]).T

for i in range(len(attributes)-1):
    for j in range(len(data[attributes[i]].values)):
        temp_input[j][i] = data[attributes[i]].values[j]

input = np.array(temp_input)
output

array([[0],
       [1],
       [0],
       [1]])

In [393]:
input_layer = 2
hidden_layer = 2
output_layer = 1
learning_rate = 1

In [394]:
weights1 = 2 * np.random.random((input_layer,hidden_layer)) - 1
bias1 = 2 * np.random.random((1,hidden_layer)) - 1

weights2 = 2 * np.random.random((hidden_layer,output_layer)) - 1
bias2 = 2 * np.random.random((1,output_layer)) - 1

In [395]:
#activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def der(x):
    return sigmoid(x) * (1 - sigmoid(x))

In [396]:
predicted = []

for epochs in range(100):
    #forward propagation
    weighted_sum1 = np.dot(input,weights1) + bias1
    curr_output1 = sigmoid(weighted_sum1)

    weighted_sum2 = np.dot(curr_output1,weights2) + bias2
    curr_output2 = sigmoid(weighted_sum2)

    error2 = output - curr_output2
    slope2 = der(curr_output2)
    delta2 = -1 / output_layer * error2 * slope2

    error1 = np.dot(delta2,weights2.T)
    slope1 = der(curr_output1)
    delta1 = error1 * slope1

    weights2 -= learning_rate * np.dot(curr_output1.T,delta2)
    weights1 -= learning_rate * np.dot(input.T,delta1)

    bias2 -= learning_rate * np.array([np.sum(delta2,axis=0)])
    bias1 -= learning_rate * np.array([np.sum(delta1,axis=0)])

    predicted = curr_output2

print(weights1)
print(weights2)

[[-0.27970082 -0.07996053]
 [ 3.51554004 -7.27406576]]
[[ 3.45330691]
 [-4.72259082]]


In [397]:
#predicted 
print(predicted)

[[0.09027394]
 [0.91102623]
 [0.08666746]
 [0.90244467]]


In [398]:
#accuracy
temp = (predicted - output) ** 2
acc = 0
for i in range(4):
    acc += temp[i][0]

print((1 - acc/4) * 100)

99.17264983445007
